### ISSUE TITLE
build error bella-gpu

### ISSUE THREAD

**Issue by PYB-SU** [giuliaguidi/bella#32]
Hi, 
when building bella-gpu (make bella-gpu) ; I've got an error 

nvcc -arch=sm_70 -O3 -maxrregcount=32 -std=c++14 -Xcompiler -fopenmp -w  -Iinclude/common/GTgraph/sprng2.0-lite/include -IloganGPU -Iseqan  -o bella hash_funcs.o Kmer.o Buffer.o fq_reader.o optlist.o src/main.cu -L/home/boelle/Documents/bella/libbloom/build -lbloom -lpthread -lbz2 -lz -D__NVCC__

seqan/seqan/score/score_matrix_dyn.h:110:489: error: template argument 1 is invalid
  110 | enum class AminoAcidScoreMatrixID : std::underlying_type_t<decltype(Find<impl::score::MatrixTags, ScoreSpecBlosum30>::VALUE)>
 
---------------------------------
Seems like some template library must be missing - Do you have an idea ?  
building without GPU is ok (make bella ); building LOGAN runs fine

platform : Ubuntu 20.04
gcc : 9.4.0
nvcc : 11.6 (quadro P1000 - architecture=sm_62)

Thanks a lot.

**Comment by PYB-SU** [comment]
I got it to compile with nvcc 10.2 + gcc 8

**Comment by giuliaguidi** [comment]
Great, I'll look into this! I found the current LOGAN implementation could break for large-ish input. A fix is underway!

Best,
Giulia
